config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  
  resources :blog_posts

  root 'blog_posts#index'

  get 'user_posts' => 'blog_posts#user_posts'
  get 'user_comments' => 'comments#user_comments'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog_post
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blog_posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, 
     :password_confirmation, :name, :username, :birthday])

    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, 
    :password_confirmation, :current_password, :name, :username, :birthday])
   end


end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  #CALLBACK used to make code more try ttc
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  # i didnt finish this code in class #before_action :

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_posts #has a matching view user_posts.html.erb
    @blog_posts = BlogPost.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :body, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_comments
    @comments = Comment.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:blog_post_id, :body, :auther, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
	def edit_destroy(blog_post)
		if current_user.id == blog_post.user_id
			edit = link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning"
			destroy = link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
			edit + destroy
     end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control', placeholder: 'Title' %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control', rows: 10, placeholder: 'Say WHAT!?!' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome <%= current_user.email %>, have a BEER!</h1>

<div class="row">

  <% @blog_posts.each_with_index do |blog_post, n| %>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><%= blog_post.title %></h3>
        </div>
        <div class="panel-body">
          <h5>By <%= link_to blog_post.user.username, user_posts_path(user_id: blog_post.user.id) %></h5>
          <h6><%= blog_post.created_at.strftime("%m/%d/%Y %I:%M %p") %></h6>
          <p><%= blog_post.body[0..250] %>...[<%= link_to 'read more', blog_post %>]</p>

        </div>

        <div class="panel-footer">
          <%= edit_destroy(blog_post) %>
        </div>

      </div>
    </div>
      <% if n.odd? %>
      </div>
      <div class="row">
    <% end %>
  <% end %>

</div>
<br>

<%= link_to 'New Blog post', new_blog_post_path %>
<br>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1><%= @blog_post.title %></h1>
				<h5><%= @blog_post.user.email %></h5>
			</div>
			<div class="panel-body">
				<p><%= @blog_post.body %></p>
			</div>
			<div class="panel-footer">
				<%= edit_destroy(@blog_post) %>
				<%= link_to 'Back', blog_posts_path %>
			</div>	
		</div>
	</div>
</div>

<%= render 'comments/form' %>

<% @blog_post.comments.each do |comment| %>
	<p><strong><%= comment.user.email %></strong> said: </p>
	<p><%= comment.body %></p>
<% end %>

app/views/blog_posts/user_posts.html.erb
<h1>Welcome <%= @user.username %>'s Blog Posts</h1>

<div class="row">

  <% @blog_posts.each_with_index do |blog_post, n| %>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><%= blog_post.title %></h3>
        </div>
        
        <div class="panel-body">
          <h5>By <%= blog_post.user.username %></h5>
          <h6><%= blog_post.created_at.strftime("%m/%d/%Y %I:%M %p") %></h6>
          <p><%= blog_post.body[0..250] %>...[<%= link_to 'read more', blog_post %>]</p>
        </div>

        <div class="panel-footer">
          <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
          <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>

      </div>
    </div>
      <% if n.odd? %>
      </div> 
      <div class="row">
    <% end %>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :blog_post_id, value: @blog_post.id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Blog post</th>
      <th>Body</th>
      <th>Auther</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.blog_post_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.auther %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blog post:</strong>
  <%= @comment.blog_post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Auther:</strong>
  <%= @comment.auther %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/user_comments.html.erb
<h1>Welcome <%= @user.username %>'s Blog Posts</h1>

<div class="row">

  <% @comments.each_with_index do |blog_post, n| %>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3></h3>
        </div>
        
        <div class="panel-body">
          <h5>By <%= blog_post.user.username %></h5>
          <h6><%= blog_post.created_at.strftime("%m/%d/%Y %I:%M %p") %></h6>
          <p><%= blog_post.body[0..250] %>...[<%= link_to 'read more', blog_post %>]</p>
        </div>

        <div class="panel-footer">
          <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
          <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>

      </div>
    </div>
      <% if n.odd? %>
      </div> 
      <div class="row">
    <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TtsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>

  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" %>

  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to 'TTS Blog', root_path, class: 'navbar-brand' %>
	    </div>

	    <% if user_signed_in? %>
		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li><%= link_to 'My Posts', user_posts_path(user_id: current_user.id) %></li>
		        <li><%= link_to 'My Comments', user_comments_path(user_id: current_user.id) %></li>
		      </ul>
		      <ul class="nav navbar-nav navbar-right">
		      	<li><%= link_to 'Peace Out', destroy_user_session_path, method: :delete%></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		<% end %>


	  </div><!-- /.container-fluid -->
	</nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>